// Browser-side loaders for the static data bundle (web/public/data/, generated by
// scripts/build_static.py). Promise-cached so concurrent callers share one fetch.
// The node parity test does NOT use this module — it fs-loads the same files itself.

const BASE = `${import.meta.env.BASE_URL}data/`;
const cache = new Map();

function fetchJson(rel) {
  if (!cache.has(rel)) {
    cache.set(rel, fetch(BASE + rel).then((res) => {
      if (!res.ok) {
        cache.delete(rel);
        throw new Error(`Data file '${rel}' failed to load (HTTP ${res.status}).`);
      }
      return res.json();
    }).catch((e) => { cache.delete(rel); throw e; }));
  }
  return cache.get(rel);
}

export const loadMeta = () => fetchJson("meta.json");
export const loadRankings = (champ, event) => fetchJson(`rankings/${champ}__${event}.json`);

const stripMeta = (o) =>
  Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith("_")));

let enginePromise = null;
export function loadEngineConfig() {
  if (!enginePromise) {
    enginePromise = fetchJson("engine.json").then((e) => ({
      events: stripMeta(e.events),
      championships: stripMeta(e.championships),
      placingScores: e.placing_scores,
      decay: e.decay,
      graphql: e.graphql,
    }));
  }
  return enginePromise;
}

// tables/{stem}.json is keyed by the CSV path events.json uses.
const loadTable = (relCsvPath) => {
  const stem = relCsvPath.split("/").pop().replace(/\.csv$/, "");
  return fetchJson(`tables/${stem}.json`);
};

// Full ranking data, with data_source delegation (road_to_ultimate reads world's file),
// mirroring fetch.fetch_championship.
export async function loadList(cfgChampionships, championship, event) {
  const source = cfgChampionships[championship]?.data_source;
  const data = await fetchJson(`lists/${source || championship}__${event}.json`);
  return source ? { ...data, championship } : data;
}

// A ready-to-use engine ctx for one (championship, event, input-event) combination:
// config + the ranking list + the result tables whatIf/requiredTargets will touch
// (the main event's, plus the selected similar event's when subEvent is set).
export async function buildCtx(championship, event, subEvent = null) {
  const cfg = await loadEngineConfig();
  const ev = cfg.events[event];
  if (!ev) throw new Error(`Unknown event '${event}'.`);

  const tablePaths = new Set([ev.result_table]);
  if (subEvent && subEvent !== "main") {
    const alt = (ev.alt_events || []).find((a) => a.key === subEvent);
    if (alt) tablePaths.add(alt.result_table);
  }
  const [list, ...tableData] = await Promise.all([
    loadList(cfg.championships, championship, event),
    ...[...tablePaths].map(loadTable),
  ]);
  const tables = Object.fromEntries([...tablePaths].map((p, i) => [p, tableData[i]]));

  return {
    ...cfg,
    tables,
    getList(c, e) {
      if (c !== championship || e !== event) throw new Error(`List not loaded: ${c}__${e}`);
      return list;
    },
  };
}
