// Golden-vector parity gate: the JS engine must reproduce the Python engine's output
// exactly. Vectors are generated by `python -m scripts.build_static` (web/parity-vectors.json)
// from the same data bundle the site ships (web/public/data/). Run with:
//     node src/engine/parity.test.mjs      (from web/)
// Any mismatch fails the build — never deploy past a red run.
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { whatIf, requiredTargets } from "./whatif.js";

const WEB = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DATA = join(WEB, "public", "data");
const readJson = (p) => JSON.parse(readFileSync(p, "utf-8"));

const engine = readJson(join(DATA, "engine.json"));
const tables = {};
for (const f of readdirSync(join(DATA, "tables"))) {
  tables[`scoring_tables/${f.replace(/\.json$/, ".csv")}`] = readJson(join(DATA, "tables", f));
}
const lists = {};
for (const f of readdirSync(join(DATA, "lists"))) {
  lists[f.replace(/\.json$/, "")] = readJson(join(DATA, "lists", f));
}

const ctx = {
  events: Object.fromEntries(Object.entries(engine.events).filter(([k]) => !k.startsWith("_"))),
  championships: Object.fromEntries(Object.entries(engine.championships).filter(([k]) => !k.startsWith("_"))),
  placingScores: engine.placing_scores,
  decay: engine.decay,
  tables,
  getList(championship, event) {
    const source = this.championships[championship]?.data_source;
    const data = lists[`${source || championship}__${event}`];
    if (!data) throw new Error(`No list data for ${championship}__${event}`);
    return source ? { ...data, championship } : data;
  },
};

// Deep compare: same keys, same values; numbers within 1e-6; JS undefined never passes
// for a Python null (the engine must emit explicit nulls).
function diff(exp, act, path = "$") {
  if (typeof exp === "number" && typeof act === "number") {
    return Math.abs(exp - act) <= 1e-6 ? null : `${path}: ${exp} != ${act}`;
  }
  if (exp === null || typeof exp !== "object") {
    return Object.is(exp, act) || exp === act ? null : `${path}: ${JSON.stringify(exp)} != ${JSON.stringify(act)}`;
  }
  if (Array.isArray(exp)) {
    if (!Array.isArray(act)) return `${path}: expected array`;
    if (exp.length !== act.length) return `${path}: length ${exp.length} != ${act.length}`;
    for (let i = 0; i < exp.length; i++) {
      const d = diff(exp[i], act[i], `${path}[${i}]`);
      if (d) return d;
    }
    return null;
  }
  if (act === null || typeof act !== "object" || Array.isArray(act)) return `${path}: expected object, got ${JSON.stringify(act)}`;
  for (const k of new Set([...Object.keys(exp), ...Object.keys(act)])) {
    const d = diff(exp[k], act[k], `${path}.${k}`);
    if (d) return d;
  }
  return null;
}

const { vectors } = readJson(join(WEB, "parity-vectors.json"));
let failures = 0;
for (const [i, v] of vectors.entries()) {
  const inp = v.inputs;
  let out = null, err = null;
  try {
    out = v.kind === "required"
      ? requiredTargets(ctx, inp.event, inp.athlete,
                        { championship: inp.championship, place: inp.place, category: inp.category })
      : whatIf(ctx, {
          event: inp.event, athlete: inp.athlete, time: inp.time,
          category: inp.category ?? "GW", place: inp.place ?? 2,
          championship: inp.championship, asOf: inp.as_of,
          qualify: inp.qualify ?? false,
          qualificationWindow: inp.qualification_window ?? false,
          subEvent: inp.sub_event ?? null,
        });
  } catch (e) {
    err = e;
  }
  let d;
  if ("expect_error" in v) {
    d = err ? diff(v.expect_error, err.message, "$.error")
            : "$.error: expected an error, engine returned a result";
  } else if (err) {
    d = `$.thrown: ${err.message}`;
  } else {
    d = diff(v.expect, out);
  }
  if (d) {
    failures += 1;
    if (failures <= 10) {
      console.error(`FAIL #${i} ${v.kind} ${inp.championship}/${inp.event} ` +
                    `${inp.athlete} ${inp.time ?? ""}\n  ${d}`);
    }
  }
}
if (failures) {
  console.error(`\nParity: ${failures}/${vectors.length} vectors FAILED`);
  process.exit(1);
}
console.log(`Parity: all ${vectors.length} vectors match the Python engine.`);
