// Quick checks for parse.js. The data-backed part reads the static bundle
// (web/public/data/, generated by `python -m scripts.build_static`) straight from disk.
// Run: node src/parse.test.mjs
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mainCode, parseQuery, bestPerf, matchAthlete, parseTime, extractSlug, deriveName, looksLikeProfile, extractName } from "./parse.js";
import { findAthlete } from "./engine/whatif.js";

const DATA = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "data");
const readJson = (p) => JSON.parse(readFileSync(join(DATA, p), "utf-8"));
let pass = 0, fail = 0;
const eq = (got, want, msg) => {
  const g = JSON.stringify(got), w = JSON.stringify(want);
  if (g === w) { pass++; } else { fail++; console.log(`FAIL ${msg}\n   got  ${g}\n   want ${w}`); };
};

// --- mainCode ---
eq(mainCode("1500m_men"), "1500", "mainCode 1500");
eq(mainCode("800m_women"), "800", "mainCode 800");
eq(mainCode("10000m_men"), "10000", "mainCode 10000");
eq(mainCode("3000mSC_women"), "3000SC", "mainCode steeple");

// --- parseTime (multi-digit minutes) ---
eq(parseTime("3:29.50"), 209.5, "parseTime 1500");
eq(parseTime("13:05.00"), 785, "parseTime 5000");
eq(parseTime("27:30.10"), 1650.1, "parseTime 10000");

// --- parseQuery ---
eq(parseQuery("What if Wightman wins a Diamond League final in 3:27.8?", "1500m_men"),
   { athlete: "What if Wightman wins a Diamond League final in 3:27.8?", place: 1, category: "DF", time: "3:27.80" }, "pq wightman");
eq(parseQuery("How does Riva look on the world ranking with a 3:31 win?", "1500m_men"),
   { athlete: "How does Riva look on the world ranking with a 3:31 win?", championship: "world", place: 1, time: "3:31.00" }, "pq world");
eq(parseQuery("women's 5000m: Smith finishes 2nd at the European Champs", "1500m_men"),
   { athlete: "women's 5000m: Smith finishes 2nd at the European Champs", championship: "road_to_birmingham", eventKey: "5000m_women", place: 2, category: "GL" }, "pq event+gender");
eq(parseQuery("steeplechase third place", "1500m_men").eventKey, "3000mSC_men", "pq steeple keeps gender");
eq(parseQuery("Does Nuguse make the Ultimate by winning a Diamond League meeting?", "1500m_men").championship,
   "road_to_ultimate", "pq ultimate");
eq(parseQuery("What if Chebet wins the World Athletics Ultimate in Budapest?", "5000m_women").championship,
   "road_to_ultimate", "pq ultimate beats 'world'");
eq(parseQuery("Wightman wins nationals in 3:34", "1500m_men").category, "B", "pq nationals -> B (national champs)");
eq(parseQuery("3rd at a national meet", "1500m_men").category, "C", "pq national meet -> C");

// --- extractName (for the unranked NL search) ---
eq(extractName("What if Jake Heyward wins nationals in 3:34"), "Jake Heyward", "name: framed + verb");
eq(extractName("Jake Heyward 3:34 at nationals"), "Jake Heyward", "name: stops at number");
eq(extractName("women's 5000m: Mary Smith finishes 2nd"), "Mary Smith", "name: strips event prefix");
eq(extractName("How does Riva look on the world ranking"), "Riva", "name: stops at 'look'");
eq(parseQuery("the 800 in 1:43.5", "5000m_women").eventKey, "800m_women", "pq 800 keeps women");

// --- extractSlug + deriveName ---
eq(extractSlug("https://worldathletics.org/athletes/great-britain/jake-heyward-14597392"), "jake-heyward-14597392", "slug from url");
eq(extractSlug("https://worldathletics.org/athletes/great-britain/jake-heyward-14597392?foo=1#bar"), "jake-heyward-14597392", "slug strips query/hash");
eq(extractSlug("  jake-heyward-14597392/  "), "jake-heyward-14597392", "slug from bare value + trailing slash");
eq(deriveName("jake-heyward-14597392"), "Jake Heyward", "name from slug");
eq(deriveName("pieter-sisk-14613049"), "Pieter Sisk", "name from slug 2");

// --- looksLikeProfile ---
eq(looksLikeProfile("https://worldathletics.org/athletes/great-britain/jake-heyward-14597392"), true, "profile url");
eq(looksLikeProfile("jake-heyward-14597392"), true, "profile bare slug");
eq(looksLikeProfile("Jake WIGHTMAN"), false, "name not profile");
eq(looksLikeProfile("Narve Gilje NORDÅS"), false, "spaced name not profile");
eq(looksLikeProfile(""), false, "empty not profile");

// --- real data (static bundle): bestPerf + matchAthlete ---
const main = async () => {
  const rk = readJson("rankings/road_to_birmingham__1500m_men.json");
  const list = rk.athletes;
  eq(matchAthlete("what if WIGHTMAN wins", list), "Jake WIGHTMAN", "match surname");
  eq(matchAthlete("how about nader", list), "Isaac NADER", "match lowercase surname");
  eq(matchAthlete("nobody here", list), null, "match miss");

  const ath = findAthlete(readJson("lists/road_to_birmingham__1500m_men.json"), "Jake WIGHTMAN");
  const best = bestPerf(ath, "1500m_men");
  // Data refreshes weekly, so assert the *rule*, not a mark: bestPerf must return the
  // main-event (code 1500) performance with the highest result score.
  const mains = ath.performances.filter((p) => p.discipline_code === "1500");
  const top = mains.reduce((a, b) => (b.result_score > a.result_score ? b : a));
  eq(best, { time: top.mark, place: String(top.place), category: top.category }, "bestPerf main-event fastest");

  console.log(`\n${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
};
main().catch((e) => { console.error("test error:", e.message); process.exit(2); });
